FROM sbtscala/scala-sbt:eclipse-temurin-25.0.4_7_1.13.0_2.13.18 AS builder

WORKDIR /build

COPY . .

WORKDIR /build/tibia-bot

RUN sbt -batch stage


FROM eclipse-temurin:25-jre

RUN mkdir -p /opt/docker

COPY --from=builder --chown=1001:0 \
    /build/tibia-bot/target/universal/stage/ \
    /opt/docker/

RUN mkdir -p /opt/docker/cache/sprites \
    && chown -R 1001:0 /opt/docker \
    && chmod -R 775 /opt/docker/cache \
    && chmod +x /opt/docker/bin/violent-bot-dedicated

WORKDIR /opt/docker

EXPOSE 8080

USER 1001:0

ENTRYPOINT ["/opt/docker/bin/violent-bot-dedicated"]
